spring:
  profiles:
    active: '"uat"'
    
---

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: tiger
    type: org.apache.commons.dbcp2.BasicDataSource
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: scott
    
---

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: tiger
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: scott
    
---
 
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    url: jdbc:mysql:///ntsp612db
    username: root
 
---
 
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql:///ntsp612db
    username: root
 
